services:
  - type: web
    name: wazifni-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: ./start.sh
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wazifni-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: wazifni-redis
          type: redis
      - key: SECRET_KEY
        sync: false
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "15"
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: "15"
      - key: JWT_ALG
        value: HS256
      - key: LOG_LEVEL
        value: info
      - key: APP_ENV
        value: production

  - type: web
    name: wazifni-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://wazifni-backend.onrender.com
      - key: NODE_ENV
        value: production

databases:
  - name: wazifni-db
    plan: free
    region: oregon

redis:
  - name: wazifni-redis
    plan: free
    region: oregon
