"""Add full_name to users table

Revision ID: 69b8e51bad4f
Revises: 5f80b5f3edd6
Create Date: 2025-10-26 07:17:31.901748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69b8e51bad4f'
down_revision: Union[str, None] = '5f80b5f3edd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
