name: Backend CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint-test-smoke:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements*.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest ruff httpx uvicorn

      - name: Lint (ruff)
        run: ruff check .

      - name: Run tests
        run: pytest -q

      - name: Smoke: boot API & hit /openapi.json
        run: |
          nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 >/tmp/api.log 2>&1 &
          for i in {1..30}; do
            curl -sf http://127.0.0.1:8000/openapi.json && break
            sleep 1
          done
          curl -sf http://127.0.0.1:8000/openapi.json | python - <<'PY'
          import sys, json
          info=json.load(sys.stdin).get("info",{})
          assert "title" in info, "Missing OpenAPI title"
          print("OpenAPI OK:", info["title"])
          PY
