name: CI
on:
  push: { branches: [main] }
  pull_request:
permissions: { contents: read }
jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: python -m pip install -U pip
      - run: pip install -r backend/requirements.txt || true
      - run: pip install pre-commit pytest ruff black mypy pip-audit "pydantic[email]" email-validator
      - run: pre-commit run --all-files || true
      - run: mypy backend/app || true
      - run: pytest -q
      - run: pip-audit || true
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: cd frontend && npm ci || npm install
      - run: cd frontend && npm run build || echo "skip build"
