name: Lint

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff pre-commit
      - name: Ruff check
        run: ruff check .
      - name: Pre-commit (ruff hooks)
        run: |
          pre-commit install-hooks
          pre-commit run --all-files
