name: Lint

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff pre-commit
      - name: Ruff check
        run: ruff check .
      - name: Pre-commit (ruff hooks)
        run: |
          pre-commit install-hooks
          pre-commit run --all-files
      - name: Commit formatted files (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "ci: apply ruff formatting [skip ci]"
            git push
          else
            echo "No formatting changes"
          fi
