name: Validate Alembic, Seed, and Smoke

on:
  push:
  pull_request:

jobs:
  backend-checks:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
          POSTGRES_DB: test_db
        ports: ["5432:5432"]
        options: >-
          --health-cmd "pg_isready -U test_user -d test_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7
        ports: ["6379:6379"]

    env:
      DATABASE_URL: postgresql+psycopg2://test_user:test_pass@localhost:5432/test_db?sslmode=disable
      PSQL_DATABASE_URL: postgresql://test_user:test_pass@localhost:5432/test_db?sslmode=disable
      PGSSLMODE: disable
      REDIS_URL: redis://localhost:6379/0
      SECRET_KEY: test-secret
      ACCESS_TOKEN_EXPIRE_MINUTES: "15"
      REFRESH_TOKEN_EXPIRE_DAYS: "15"
      JWT_ALG: HS256
      LOG_LEVEL: info
      APP_ENV: ci

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt

      - name: Run Alembic migrations
        working-directory: backend
        run: |
          PYTHONPATH=. alembic upgrade head

      - name: Seed test database
        working-directory: backend
        run: |
          PYTHONPATH=. python ../scripts/seed.py
          psql "$PSQL_DATABASE_URL" -c "\\d users"

      - name: Start API for smoke tests
        working-directory: backend
        run: |
          PYTHONPATH=. uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          echo $! > ../uvicorn.pid
          for i in {1..12}; do
            if curl --fail --silent http://127.0.0.1:8000/healthz > /dev/null; then
              echo "API is up"
              break
            fi
            echo "Waiting for API to be ready..."
            sleep 5
          done

      - name: Run smoke tests
        env:
          BASE_URL: http://127.0.0.1:8000
        run: |
          ./scripts/smoke.sh

      - name: Stop API
        if: always()
        run: |
          if [ -f uvicorn.pid ]; then
            kill "$(cat uvicorn.pid)" || true
          fi
